components:
  schemas:
    Dog:
      properties:
        kind:
          $ref: '#/components/schemas/DogType'
        name:
          title: Name
          type: string
        pk:
          title: Pk
          type: integer
      required:
      - name
      - pk
      - kind
      title: Dog
      type: object
    DogType:
      enum:
      - terrier
      - bulldog
      - dalmatian
      title: DogType
      type: string
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    Timestamp:
      properties:
        id:
          title: Id
          type: integer
        timestamp:
          title: Timestamp
          type: integer
      required:
      - id
      - timestamp
      title: Timestamp
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: FastAPI
  version: 0.1.0
openapi: 3.1.0
paths:
  /:
    get:
      description: Service root with empty json as response.
      operationId: root__get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Root
  /dog:
    get:
      operationId: get_dogs_dog_get
      parameters:
      - in: query
        name: kind
        required: false
        schema:
          anyOf:
          - $ref: '#/components/schemas/DogType'
          - type: 'null'
          title: Kind
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Dog'
                title: Response Get Dogs Dog Get
                type: array
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Dogs
    post:
      operationId: add_dog_dog_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dog'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dog'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Add Dog
  /dog/{pk}:
    get:
      operationId: get_dog_dog__pk__get
      parameters:
      - in: path
        name: pk
        required: true
        schema:
          title: Pk
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dog'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Dog
    patch:
      operationId: update_dog_dog__pk__patch
      parameters:
      - in: path
        name: pk
        required: true
        schema:
          title: Pk
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dog'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dog'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Update Dog
  /post:
    post:
      description: Save timestamp to storage and return it.
      operationId: post_post_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Timestamp'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Timestamp'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Post
